name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
      
jobs:
  check-aplication:
    #Maquina virtual na onde é realizada as operações de CI
    runs-on: ubuntu-latest
    steps:
      #Pega os dados que foi dado o push e insere na maquina virtual do ubuntu
      - uses: actions/checkout@v2
      #Pega ambiente da maquina e coloca o go para funcionar
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go